theme: jekyll-theme-slate
title: Planet in a Bottle
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
google_analytics: UA-153197658-1
include:
  - index.md
  - privacypolicy.md
